### ISSUE TITLE
better motor classes

### ISSUE THREAD

**Issue by matt-mekha** [awtybots/FRC-Utils#11]
- abstracted motor math
- allow data injection for simulation
- mesh nicely with other library classes

**Comment by matt-mekha** [comment]
@DGKSK8LIFE 

For each motor controller that we plan on using (TalonFX and TalonSRX), we need a class that does the following:
- inherits the corresponding CTRE class
- contains useful info like max RPM of that motor and such
- gear ratio is part of the constructor and is stored as a property for use in math
- provides some handy functions like getting/setting gearbox output RPM
- overload the way PID works
- give the motor class a data injection mode that will help writing JUnit tests, for example:
```kt
motor.simulationMode = true
motor.set(1.0)
assert(motor.motorRPM > 0)
assert(motor.motorRPM * gearboxRatio == motor.outputRPM)
```

**Comment by DGKSK8LIFE** [comment]
Ok. Do you mind if I write this in java? @matt-mekha

**Comment by matt-mekha** [comment]
no must be kotlin @DGKSK8LIFE

**Comment by DGKSK8LIFE** [comment]
Why? @matt-mekha

**Comment by DGKSK8LIFE** [comment]
They can interop pretty well @matt

**Comment by AlexDvorak** [comment]
[TalonSRX class reference](https://www.ctr-electronics.com/downloads/api/java/html/classcom_1_1ctre_1_1phoenix_1_1motorcontrol_1_1can_1_1_talon_s_r_x.html)
[TalonFX class reference](https://www.ctr-electronics.com/downloads/api/java/html/classcom_1_1ctre_1_1phoenix_1_1motorcontrol_1_1can_1_1_talon_f_x.html)
[CTRE tutorial on using built in PID controller](https://phoenix-documentation.readthedocs.io/en/latest/ch16_ClosedLoop.html)
