### ISSUE TITLE
run tests as condition for pull requests

### ISSUE THREAD

**Issue by matt-mekha** [awtybots/FRC-Utils#6]
just a `gradlew test` should be good

**Comment by DGKSK8LIFE** [comment]
We could write a script to automate tests. I think in some instances (where we're doing lots of arithmetic/handling input), we should write formal test cases.

**Comment by DGKSK8LIFE** [comment]
@matt-mekha [this](https://github.com/marketplace/actions/gradle-command) sample runs the build script, should I just use it or adapt it to run the `gradlew test` command?

**Comment by matt-mekha** [comment]
> @matt-mekha [this](https://github.com/marketplace/actions/gradle-command) sample runs the build script, should I just use it or adapt it to run the `gradlew test` command?

Yeah just change it to test and it should be good

**Comment by DGKSK8LIFE** [comment]
ok sounds good. and not `gradlew` just `gradle`, right?

**Comment by matt-mekha** [comment]
> ok sounds good. and not `gradlew` just `gradle`, right? 

Idk what the dependency uses so just change build to test

**Comment by DGKSK8LIFE** [comment]
matt I don't have privileges to push a new upstream branch. I need them to make the PR. Ty. tbh just gimme owner I won't do anything dumb with it

**Comment by DGKSK8LIFE** [comment]
are you awake? @matt-mekha :joy:

**Comment by DGKSK8LIFE** [comment]
Fixed in #16
